version: "2"
services:
  gradle:
    image: gradle:5.4-jdk8
    volumes:
      - ./server:/app/server
      - gradle-cache:/home/gradle/.gradle
    working_dir: /app/server
    environment:
      DB_JDBC_URL: jdbc:postgresql://db/postgres
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
  app:
    extends:
      service: gradle
    container_name: docker-server
    command: ["gradle", "bootRun"]
    depends_on:
      - db
    expose:
      - 8080
    ports:
      - 8080:8080
  nginx:
    image: nginx:alpine
    container_name: webserver
    ports:
      - 8081:80
      - 443:443
    restart: always
  db:
    image: postgres:latest
    container_name: postgres-stubb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_DATABASE: postgres
    volumes:
      - ./dev/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - 5432:5432
    restart: always

volumes:
  gradle-cache:
  database_data:
    driver: local
